-- 메모리 db는 앱 실행 시점에 테이블을 만들어주어야 에러가 안난다.

drop table if exists item cascade;

create table item
(
    id bigint generated by default as identity,
    item_name varchar(10),
    price integer,
    quantity integer,
    primary key (id)
);